# GENERATED by script/update-cask.sh on release. Install:
#   brew tap juniorsaldanha/hyprland-darwin https://github.com/juniorsaldanha/hyprland-darwin
#   brew install --cask hyprdarwin
cask "hyprdarwin" do
  version "0.1.0"
  sha256 "808eabe53bc2459e99170aa6be1b70ce9ee7b52b156211940940c755a840a7f5"

  url "https://github.com/juniorsaldanha/hyprland-darwin/releases/download/v#{version}/HyprDarwin-#{version}.zip"
  name "HyprDarwin"
  desc "Hyprland-like tiling window manager: tiling, status bar, borders and plugins"
  homepage "https://juniorsaldanha.github.io/hyprland-darwin/"

  depends_on macos: :ventura

  app "HyprDarwin.app"
  binary "hypr"

  # Signed ad hoc (no Apple Developer ID): without this, Gatekeeper refuses to open it
  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{appdir}/HyprDarwin.app", "#{staged_path}/hypr"]
  end

  uninstall quit: "dev.hyprdarwin"

  zap trash: [
    "~/.config/hyprland-darwin",
    "~/Library/Logs/hyprland-darwin",
  ]
end
