# GENERATED by script/update-cask.sh on release. Install:
#   brew tap juniorsaldanha/hyprland-darwin https://github.com/juniorsaldanha/hyprland-darwin
#   brew install --cask hyprdarwin
cask "hyprdarwin" do
  version "0.2.0"
  sha256 "c027b29adda8b4acf962f0c950c544ac7c7310713d331afa6db0ef7b479c6b86"

  url "https://github.com/juniorsaldanha/hyprland-darwin/releases/download/v#{version}/HyprDarwin-#{version}.zip"
  name "HyprDarwin"
  desc "Hyprland-like tiling window manager: tiling, status bar, borders and plugins"
  homepage "https://juniorsaldanha.github.io/hyprland-darwin/"

  depends_on macos: :ventura

  app "HyprDarwin.app"
  binary "hypr"
  binary "shell-completion/zsh/_hypr", target: "#{HOMEBREW_PREFIX}/share/zsh/site-functions/_hypr"
  binary "shell-completion/bash/hypr", target: "#{HOMEBREW_PREFIX}/etc/bash_completion.d/hypr"
  binary "shell-completion/fish/hypr.fish", target: "#{HOMEBREW_PREFIX}/share/fish/vendor_completions.d/hypr.fish"

  # Signed ad hoc (no Apple Developer ID): without this, Gatekeeper refuses to open it
  postflight_steps do
    run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{appdir}}/HyprDarwin.app"], must_succeed: false
    run "/usr/bin/xattr", args: ["-d", "com.apple.quarantine", "{{staged_path}}/hypr"], must_succeed: false
  end

  Dir["#{staged_path}/manpage/*.1"].each { |page| manpage page }

  uninstall quit: "dev.hyprdarwin"

  zap trash: [
    "~/.config/hyprland-darwin",
    "~/Library/Logs/hyprland-darwin",
  ]
end
