#!/usr/bin/env bash
# Writes Casks/hyprdarwin.rb for a released version. Run by .github/workflows/release.yml.
#   script/update-cask.sh <version> <sha256 of HyprDarwin-<version>.zip>
set -euo pipefail
cd "$(dirname "$0")/.."
version="$1"
sha="$2"
mkdir -p Casks
cat > Casks/hyprdarwin.rb <<CASK
# GENERATED by script/update-cask.sh on release. Install:
#   brew tap juniorsaldanha/hyprland-darwin https://github.com/juniorsaldanha/hyprland-darwin
#   brew install --cask hyprdarwin
cask "hyprdarwin" do
  version "$version"
  sha256 "$sha"

  url "https://github.com/juniorsaldanha/hyprland-darwin/releases/download/v#{version}/HyprDarwin-#{version}.zip"
  name "HyprDarwin"
  desc "Hyprland-like tiling window manager: tiling, status bar, borders and plugins"
  homepage "https://juniorsaldanha.github.io/hyprland-darwin/"

  depends_on macos: :ventura

  app "HyprDarwin.app"
  binary "hypr"

  # Signed ad hoc (no Apple Developer ID): without this, Gatekeeper refuses to open it
  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{appdir}/HyprDarwin.app", "#{staged_path}/hypr"]
  end

  uninstall quit: "dev.hyprdarwin"

  zap trash: [
    "~/.config/hyprland-darwin",
    "~/Library/Logs/hyprland-darwin",
  ]
end
CASK
echo "Wrote Casks/hyprdarwin.rb ($version)"
